bind r source-file ~/.tmux.conf
#new windows index
set -g base-index 1

# 256 color support
set -g default-terminal "tmux-256color"

#status bar
set -g status-style 'bg=#121212 fg=#97bedc'

#clipboard
tmux_conf_copy_to_os_clipboard=true

#vim-mode copy/paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

#vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

#resize panes
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

#visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on
